name: Tag deploy success
description: Tag deployment success

author: kemadev
branding:
  icon: tag
  color: blue

inputs:
  deployed-ref:
    description: The ref that was deployed
    required: true

runs:
  using: composite
  steps:
    - name: Tag deploy success
      id: tag-deploy-success
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "kemadev+github-actions[bot]@users.noreply.github.com"
        git tag -a "deploy-success-${{ inputs.deployed-ref }}-${{ github.run_id }}" -m "Deploy success"
        git push --tags
  # backlink-pr:
  #   name: Backlink PR
  #   if: ${{ github.event.inputs.force-rollback-to == '' }}
  #   permissions:
  #     pull-requests: write
  #   runs-on: ubuntu-latest
  #   # Do not fail the workflow if a QoL step fails
  #   continue-on-error: true
  #   steps:
  #     - name: Checkout
  #       id: checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Backlink PR
  #       id: backlink-pr
  #       env:
  #         GH_TOKEN: ${{ github.token }}
  #       # Assuming we use format `<PR title> (#<PR number>)`, which is the organization's convention
  #       run: |
  #         declare pr_number
  #         pr_number="$(git log -1 --pretty=format:"%s" ${{ github.sha }} | grep -oP '(?<=\(#)\d+(?=\)$)')"
  #         if [[ -z "${pr_number}" ]]; then
  #           echo "No PR number found in commit message"
  #           exit 0
  #         fi
  #         gh pr comment "${pr_number}" --repo "${{ github.repository }}" --body "This PR has been deployed from **${{ github.ref_name }}**. [View deployment details](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
