name: Tag deploy success
description: Tag deployment success

author: kemadev
branding:
  icon: tag
  color: blue

inputs:
  deployed-ref:
    description: The ref that was deployed
    required: true

runs:
  using: composite
  steps:
    - name: Tag deploy success
      id: tag-deploy-success
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "kemadev+github-actions[bot]@users.noreply.github.com"
        git clone https://github.com/${{ github.repository }} ${{ runner.temp }}/repo
        cd ${{ runner.temp }}/repo
        rm -rf *
        cp -r ${{ github.workspace }}/* .
        git add .
        git commit -m "Sync wiki - ${{ github.run_id }}"
        git push
