name: Tag deploy success
description: Tag deployment success

author: kemadev
branding:
  icon: tag
  color: blue

inputs:
  deployed-ref:
    description: The ref that was deployed
    required: true

runs:
  using: composite
  steps:
    - name: Tag deploy success
      id: tag-deploy-success
      shell: bash
      env:
        DEPLOYED_REF: ${{ inputs.deployed-ref }}
        RUN_ID: ${{ github.run_id }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "kemadev+github-actions[bot]@users.noreply.github.com"
        git tag -a "deploy-success-${DEPLOYED_REF}-${RUN_ID}" -m "Deploy success"
        git push --tags
