name: Tag deploy success
description: Tag deployment success

author: kemadev
branding:
  icon: tag
  color: blue

runs:
  using: composite
  steps:
    - name: Tag deploy success
      id: tag-deploy-success
      shell: bash
      env:
        GHA_BOT_NAME: github-actions[bot]
        GHA_BOT_EMAIL: kemadev+github-actions[bot]@users.noreply.github.com
      run: |
        git config user.name "${{ env.GHA_BOT_NAME }}"
        git config user.email "${{ env.GHA_BOT_EMAIL }}"
        git tag -a "deploy-success-${{ github.ref_name }}-${{ github.run_id }}" -m "Deploy success"
        git push --tags
