name: Tag deploy success
description: Tag deployment success

author: kemadev
branding:
  icon: tag
  color: blue

inputs:
  deployed-ref:
    description: The ref that was deployed
    required: true

runs:
  using: composite
  steps:
    - name: Tag deploy success
      id: tag-deploy-success
      shell: bash
      run: |
        git config user.name "$github-actions[bot]"
        git config user.email "kemadev+github-actions[bot]@users.noreply.github.com"
        git tag -a "deploy-success-${{ inputs.deployed-ref }}-${{ github.run_id }}" -m "Deploy success"
        git push --tags
