name: Release
description: Release new version

author: kemadev
branding:
  icon: tag
  color: blue

inputs:
  artifact-name:
    description: Name of build artifact
    required: false
    default: build-outputs
  goreleaser-dist-dir:
    description: Directory where goreleaser artifacts are stored
    required: false
    default: dist/goreleaser

  release-please-config-file:
    description: Path to the release-please configuration file
    required: false
    default: config/release-please/release-please-config.json
  release-please-manifest-file:
    description: Path to the release-please manifest file
    required: false
    default: config/release-please/release-please-manifest.json

runs:
  using: composite
  steps:
    - name: Checkout reusable workflow scripts and configs
      id: checkout-reusable-scripts-and-configs
      uses: kemadev/workflows-and-actions/.github/actions/checkout-reusable-scripts-and-configs@main
      with:
        reusable-diretories: 'config/reusable'
    # - name: Download build artifacts
    #   id: download-build-artifacts
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: ${{ inputs.artifact-name }}
    #     path: ${{ inputs.goreleaser-dist-dir }}
    - name: Release
      id: release
      uses: googleapis/release-please-action@v4
      with:
        config-file: ${{ inputs.release-please-config-file }}
        manifest-file: ${{ inputs.release-please-manifest-file }}
    - name: Upload release artifacts
      id: upload-release-artifacts
      shell: bash
      if: ${{ steps.release.outputs.release_created }}
      env:
        GH_TOKEN: ${{ github.token }}
        GORELEASER_DIST_DIR: ${{ inputs.goreleaser-dist-dir }}
        TAG_NAME: ${{ steps.release.outputs.tag_name }}
      run: |
        declare artifacts
        artifacts=$(jq '.[] | select(.type == "Archive" or .type == "SBOM" or .type == "Checksum") | .path' ${GORELEASER_DIST_DIR}/artifacts.json | tr -d '"' | tr '\n' ' ')
        echo "Uploading artifacts: ${artifacts}"
        gh release upload "${TAG_NAME}" ${artifacts}
