rules:
  anchors: enable
  braces:
    level: warning
    forbid: non-empty
  brackets:
    level: warning
    forbid: false
  colons: enable
  commas: enable
  comments:
    level: warning
    min-spaces-from-content: 1
  comments-indentation:
    level: warning
  document-end:
    level: warning
    present: false
  document-start:
    level: warning
    present: false
  empty-lines: enable
  empty-values: enable
  float-values: enable
  hyphens: enable
  indentation:
    spaces: 2
  key-duplicates: enable
  key-ordering: disable
  line-length:
    level: warning
    max: 400
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values:
    level: warning
  quoted-strings:
    level: warning
    quote-type: single
    required: only-when-needed
  trailing-spaces: enable
  truthy:
    level: warning
    check-keys: false
