# Read more about `labeler.yaml` [here](https://github.com/actions/labeler)

area/worflows:
  - changed-files:
      - any-glob-to-any-file: [.github/workflows/**, .github/actions/**]

area/dependencies:
  - changed-files:
      - any-glob-to-any-file: [go.mod, go.sum]

area/infra:
  - changed-files:
      - any-glob-to-any-file: [deploy/**]

type/bug:
  - head-branch: [^fix/, ^hotfix/]

type/feature:
  - head-branch: [^feat/]

env/dev:
  - base-branch: [^dev]

env/next:
  - base-branch: [^next]

env/prod:
  - base-branch: [^main]
