name: Get list of deploy configurations
description: Get list of deploy configurations from the deploy directory

author: kemadev
branding:
  icon: list
  color: blue

inputs:
  force-rollback:
    description: Force rollback to a specific commit
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout to latest sucessful deploy
      id: checkout-to-latest-sucessful-deploy
      shell: bash
      run: |
        export checkout_target=""
        if [ "${{ github.event.inputs.force-rollback }}" == "latest" ]; then
          checkout_target="$(git tag --list "${{ env.GIT_DEPLOYMENT_SUCCESS_TAG_PREFIX }}${{ github.ref_name }}-*" | sort -V | tail -n 1)"
        else
          checkout_target="${FORCE_ROLLBACK}"
        fi
        git checkout "${checkout_target}"
