name: Get list of deploy configurations
description: Get list of deploy configurations from the deploy directory

author: kemadev
branding:
  icon: list
  color: blue

inputs:
  git-deployment-success-tag-prefix:
    description: Prefix for deployment success tags
    required: false
    default: deploy-success-
  force-rollback:
    description: Force rollback to a specific commit
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout to latest sucessful deploy
      id: checkout-to-latest-sucessful-deploy
      shell: bash
      run: |
        echo "Checking out to latest successful deploy with tag prefix: ${{ inputs.git-deployment-success-tag-prefix }} and force-rollback: ${{ github.event.inputs.force-rollback }}"
        export checkout_target=""
        if [ "${{ github.event.inputs.force-rollback }}" == "latest" ]; then
          git status
          git tag --list "${{ inputs.git-deployment-success-tag-prefix }}${{ github.ref_name }}-*" | sort -V | tail -n 1
          checkout_target="$(git tag --list "${{ inputs.git-deployment-success-tag-prefix }}${{ github.ref_name }}-*" | sort -V | tail -n 1)"
        else
          checkout_target="${{ github.event.inputs.force-rollback }}"
        fi
        echo "Checking out to ${checkout_target}"
        git checkout "${checkout_target}"
