name: Get list of deploy configurations
description: Get list of deploy configurations from the deploy directory

author: kemadev
branding:
  icon: list
  color: blue

inputs:
  git-deployment-success-tag-prefix:
    description: Prefix for deployment success tags
    required: false
    default: deploy-success-
  force-rollback-to:
    description: Force rollback to a specific checkout target (use `latest` or leave empty for latest successful deploy)
    required: false
    default: 'latest'

runs:
  using: composite
  steps:
    - name: Checkout to latest sucessful deploy
      id: checkout-to-latest-sucessful-deploy
      shell: bash
      run: |
        echo "Checking out to latest successful deploy with tag prefix: ${{ inputs.git-deployment-success-tag-prefix }} and force-rollback-to: ${{ github.event.inputs.force-rollback-to }}"
        # Avoid noisy warning message
        git config --global advice.detachedHead false
        declare checkout_target=""
        if [[ "${{ github.event.inputs.force-rollback-to }}" == "latest" || "${{ github.event.inputs.force-rollback-to }}" == "" ]]; then
          git tag --list "deploy-success-main-*" | sort -V | tail -n 1
          git log --oneline --decorate --graph --all
          checkout_target="$(git tag --list "${{ inputs.git-deployment-success-tag-prefix }}${{ github.ref_name }}-*" | sort -V | tail -n 1)"
        else
          checkout_target="${{ github.event.inputs.force-rollback-to }}"
        fi
        echo "Checking out to ${checkout_target}"
        git checkout "${checkout_target}"
