name: Run Pulumi command for Go
description: Run Pulumi command for Go

author: kemadev
branding:
  icon: upload-cloud
  color: blue

inputs:
  build-artifact-name:
    description: Name of build artifact
    required: false
    default: build-outputs
  build-artifact-dir:
    description: Directory where goreleaser artifacts are stored
    required: false
    default: dist/goreleaser
  deploys-base-dir:
    description: Directory where deploy configurations are stored
    required: false
    default: deploy
  command:
    description: Which command to run
    required: true
    default: preview
  environment:
    description: Environment to deploy to
    required: true
    default: dev

runs:
  using: composite
  steps:
    - run: |
        echo command is ${{ inputs.command }}
        echo environment is ${{ inputs.environment }}
        exit 1
      shell: bash
    # - name: Download build artifacts
    #   id: download-build-artifacts
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: ${{ inputs.build-artifact-name }}
    #     path: ${{ inputs.build-artifact-dir }}
    # - name: Set up Go
    #   id: setup-go
    #   uses: actions/setup-go@v5
    #   with:
    #     go-version-file: ${{ inputs.deploys-base-dir }}/${{ matrix.deploy }}/go.mod
    #     cache-dependency-path: ${{ inputs.deploys-base-dir }}/${{ matrix.deploy }}/go.sum
    # - name: Configure AWS credentials
    #   id: configure-aws-credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   continue-on-error: false
    #   with:
    #     role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
    #     aws-region: ${{ secrets.AWS_REGION }}
    #     role-session-name: gha-${{ github.repository }}-${{ inputs.environment }}-${{ github.run_id }}
    #     mask-aws-account-id: true
    # - name: Update Cloud resources
    #   id: update-cloud-resources
    #   uses: pulumi/actions@v6
    #   with:
    #     command: ${{ inputs.command }}
    #     work-dir: ${{ inputs.deploys-base-dir }}/${{ matrix.deploy }}
    #     refresh: true
    #     comment-on-summary: true
    #     comment-on-pr: true
    #     edit-pr-comment: false
    #     always-include-summary: true
    #     stack-name: ${{ inputs.environment }}
    #     github-token: ${{ github.token }}
