name: Deploy Go code
description: Deploy Go code

author: kemadev
branding:
  icon: upload-cloud
  color: blue

inputs:
  build-artifact-name:
    description: Name of build artifact
    required: false
    default: build-outputs
  build-artifact-dir:
    description: Directory where goreleaser artifacts are stored
    required: false
    default: dist/goreleaser
  deploys-base-dir:
    description: Directory where deploy configurations are stored
    required: false
    default: deploy
  noop:
    description: Whether to perform a dry run
    required: false
    default: 'false'
  environment:
    description: Environment to deploy to
    required: true
    default: dev

runs:
  using: composite
  steps:
    - name: Download build artifacts
      id: download-build-artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.build-artifact-name }}
        path: ${{ inputs.build-artifact-dir }}
    - name: Debug
      env:
        FOO: ${{ inputs.noop == 'true' && 'preview' || 'up' }}
      run: |
        echo "noop: ${{ inputs.noop }}"
        echo "FOO: $FOO"
    # - name: Set up Go
    #   id: setup-go
    #   uses: actions/setup-go@v5
    #   with:
    #     go-version-file: ${{ inputs.deploys-base-dir }}/${{ matrix.deploy }}/go.mod
    #     cache-dependency-path: ${{ inputs.deploys-base-dir }}/${{ matrix.deploy }}/go.sum
    # - name: Configure AWS credentials
    #   id: configure-aws-credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   continue-on-error: false
    #   with:
    #     role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
    #     aws-region: ${{ secrets.AWS_REGION }}
    #     role-session-name: gha-${{ github.repository }}-${{ inputs.environment }}-${{ github.run_id }}
    #     mask-aws-account-id: true
    # - name: Update Cloud resources
    #   id: update-cloud-resources
    #   uses: pulumi/actions@v6
    #   with:
    #     command: ${{ inputs.noop == 'true' && 'preview' || 'up' }}
    #     work-dir: ${{ inputs.deploys-base-dir }}/${{ matrix.deploy }}
    #     comment-on-pr: true
    #     comment-on-summary: true
    #     stack-name: ${{ inputs.environment }}
    #     github-token: ${{ github.token }}
