name: Build Go code
description: Build Go code

author: kemadev
branding:
  icon: box
  color: blue

inputs:
  artifact-name:
    description: Name of build artifact
    required: false
    default: build-outputs
  goreleaser-render-config-script-dir:
    description: Directory where the goreleaser render config script is stored
    required: false
    default: .github/script/reusable/render-goreleaser-config
  goreleaser-dist-dir:
    description: Directory where goreleaser artifacts are stored
    required: false
    default: dist/goreleaser
  upload-artifact:
    description: Whether to upload the build artifact
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Checkout reusable workflow scripts and configs
      id: checkout-reusable-scripts-and-configs
      uses: kemadev/workflows-and-actions/.github/actions/checkout-reusable-scripts-and-configs@main
    - name: Set up Go
      id: setup-go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.goreleaser-render-config-script-dir }}/go.mod
        cache-dependency-path: ${{ inputs.goreleaser-render-config-script-dir }}/go.sum
    - name: Get syft go.mod for cache key
      id: get-syft-go-mod-for-cache-key
      shell: bash
      run: |
        declare syft_go_mod_path="${{ runner.temp }}/syft-go.mod"
        curl --silent https://raw.githubusercontent.com/anchore/syft/refs/heads/main/go.mod > "${syft_go_mod_path}"
        echo "syft-go-mod-path=${syft_go_mod_path}" > "${GITHUB_OUTPUT}"
      working-directory: ${{ inputs.goreleaser-render-config-script-dir }}
    - name: Cache Go install
      id: cache-go-install
      uses: actions/cache@v4
      with:
        path: |
          ~/go/bin
        key: ${{ runner.os }}-go-install-${{ hashFiles('${{ steps.get-syft-go-mod-for-cache-key.outputs.syft-go-mod-path }}') }}
    - name: Render goreleaser config
      id: render-goreleaser-config
      shell: bash
      env:
        GORELEASER_CONFIG_TEMPLATE_DIR: ${{ github.workspace }}/config/reusable
        GORELEASER_CONFIG_TEMPLATE_FILENAME: .goreleaser.yaml.go.tmpl
        GORELEASER_CONFIG_OUTPUT_FILE: ${{ github.workspace }}/config/reusable/.goreleaser.yaml
        BUILDS_DIR_PARENT: ${{ github.workspace }}
        BUILDS_DIR: cmd
      working-directory: ${{ inputs.goreleaser-render-config-script-dir }}
      run: |
        mkdir -p ${{ env.GORELEASER_CONFIG_TEMPLATE_DIR }}
        go run ./...
    - name: Install syft
      id: install-syft
      shell: bash
      run: |
        go install github.com/anchore/syft/cmd/syft@latest
    - name: Build code
      id: build
      uses: goreleaser/goreleaser-action@v6
      with:
        args: release --config ${{ github.workspace }}/config/reusable/.goreleaser.yaml --clean --snapshot --skip announce --skip publish --skip validate
      env:
        # make goreleaser think it's a new version and generate all artifacts
        GORELEASER_PREVIOUS_TAG: v0.0.0-dummy
        GORELEASER_CURRENT_TAG: v0.0.1-dummy
    - name: Upload build artifacts
      id: upload-build-artifacts
      if: ${{ inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.goreleaser-dist-dir }}
        if-no-files-found: error
        retention-days: 1
