name: Checkout reusable scripts
description: Get reusable scripts from the reusable workflows repository

author: kemadev
branding:
  icon: download-cloud
  color: blue

runs:
  using: composite
  steps:
      - name: Backup .git directory
        id: backup-git-dir
        shell: bash
        run: |
          cp -r .git "${RUNNER_TEMP}/.git"
      - name: Checkout reusable workflow scripts
        id: checkout-reusable-scripts
        uses: actions/checkout@v4
        with:
          repository: kemadev/workflows-and-actions
          sparse-checkout: .github/script/reusable
      - name: Restore .git directory
        shell: bash
        id: restore-git-dir
        run: |
          rm -rf .git
          mv "${RUNNER_TEMP}/.git" .git
