name: Docker - CI

on:
  pull_request:
    paths:
      - "**/*Dockerfile"
  workflow_call: {}
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

env:
  FINDINGS_JSON_OUTPUT: ./dist/docker.json

jobs:
  lint-dockerfiles:
    name: Lint Dockerfiles
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Lint Dockerfiles
        id: lint-dockerfiles
        uses: hadolint/hadolint-action@master
        with:
          recursive: true
          format: json
          output-file: ${{ env.FINDINGS_JSON_OUTPUT }}
      - name: Report findings
        id: report-findings
        run: |
          if [ -f "${FINDINGS_JSON_OUTPUT}" ] && [ "$(cat "${FINDINGS_JSON_OUTPUT}")" != "[]" ]; then
            jq -r '.[] | "::error file=\(.file),line=\(.line),col=\(.column)::\(.message) - \(.code)"' "${FINDINGS_JSON_OUTPUT}"
            exit 1
          fi
