name: GitHub Actions - CI

on:
  schedule:
    # Each day at 3:00 AM
    - cron: 0 3 * * *
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - unlocked
    paths:
      - .github/workflows/*
  workflow_call: {}
  workflow_dispatch:
    inputs:
      additional-args:
        description: Additional arguments to pass to the actionlint command
        required: false
        default: ''

defaults:
  run:
    shell: bash

jobs:
  lint-workflow-files:
    name: Lint workflow files
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Lint workflow files
        id: lint-workflow-files
        uses: docker://rhysd/actionlint:latest
        env:
          ADDITIONAL_ARGS: ${{ github.event.inputs.additional-args }}
        with:
          # Enable annotations, see https://github.com/rhysd/actionlint/blob/v1.7.7/docs/usage.md#example-error-annotation-on-github-actions
          args: |
            -format "{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Message}}%0A```%0A{{replace $err.Snippet \"\\n\" \"%0A\"}}%0A```\n{{end}}" ${{ env.ADDITIONAL_ARGS }}
