name: Global - CI

on:
  pull_request: {}
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  scan-secrets:
    name: Scan secrets
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Scan secrets
        uses: trufflesecurity/trufflehog@main

  scan-code:
    name: Scan code
    container:
      image: semgrep/semgrep
    if: github.actor != 'dependabot[bot]'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Scan code
        env:
          FINDINGS_JSON_OUTPUT: ./dist/semgrep.json
        run: |
          declare scan_returned_findings=false
          semgrep scan --config auto --error --json-output "${FINDINGS_JSON_OUTPUT}" || scan_returned_findings=true
          if [ "${scan_returned_findings}" = true ]; then
            if [ -f "${FINDINGS_JSON_OUTPUT}" ]; then
              jq -r '.results[] | "::error file=\(.path),line=\(.start.line),col=\(.start.col),endLine=\(.end.line),endCol=\(.end.col)::\(.extra.message) - \(.check_id)"' "${FINDINGS_JSON_OUTPUT}"
            fi
            exit 1
          fi
