name: Go - CD

on:
  workflow_dispatch:
    inputs:
      command:
        description: Command to run
        default: up
      sha:
        description: SHA to deploy
        default: ${{ github.sha }}
      ref:
        description: Ref to deploy
        default: ${{ github.ref }}
      base_ref:
        description: Base ref to deploy
        default: ${{ github.ref }}
      enable_rollback:
        description: Enable rollback
        default: true
  workflow_call:
    inputs:
      command:
        description: Command to run
        default: up
      sha:
        description: SHA to deploy
        default: ${{ github.sha }}
      ref:
        description: Ref to deploy
        default: ${{ github.ref }}
      base_ref:
        description: Base ref to deploy
        default: ${{ github.ref }}
      enable_rollback:
        description: Enable rollback
        default: true

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    uses: kemadev/workflows-and-actions/.github/actions/go-pulumi@main
    with:
      command: ${{ inputs.command }}
      sha: ${{ inputs.sha }}
      ref: ${{ inputs.ref }}
      base_ref: ${{ inputs.base_ref }}

  tag-deploy-success:
    name: Tag deploy success
    needs:
      - deploy
    if: ${{ inputs.base_ref == 'main' && inputs.command == 'up' && needs.deploy.result == 'success' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Tag deploy success
        id: tag-deploy-success
        uses: kemadev/workflows-and-actions/.github/actions/tag-deploy-success@main
        with:
          deployed-ref: ${{ inputs.base_ref }}

  prepare-rollback:
    name: Prepare rollback
    needs:
      - deploy
    runs-on: ubuntu-latest
    outputs:
      latest-deploy-success-tag: ${{ steps.prepare-rollback.outputs.latest-deploy-success-tag }}
    permissions:
      contents: read
      deployments: write
    needs: deploy
    if: ${{ always() && inputs.command == 'up' && inputs.enable_rollback == 'true' }}
    steps:
      shell: bash
      run: |
        declare latest_deploy_success_tag
        latest_deploy_success_tag="$(git tag --list "${{ inputs.git-deployment-success-tag-prefix }}${{ inputs.branch }}-*" | sort -V | tail -n 1)"
        if [[ -z "${latest_deploy_success_tag}" ]]; then
          echo "No successful deployment found for branch ${{ inputs.branch }}"
          exit 1
        fi
        echo "Latest successful deployment tag is ${latest_deploy_success_tag}"
        echo "latest-deploy-success-tag=${latest_deploy_success_tag}" >> "${GITHUB_OUTPUT}"

  rollback:
    name: Rollback
    needs:
      - prepare-rollback
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    needs: prepare-rollback
    uses: kemadev/workflows-and-actions/.github/actions/go-pulumi@main
    with:
      command: up
      sha: ${{ needs.prepare-rollback.outputs.latest-deploy-success-tag }}
      ref: ${{ needs.prepare-rollback.outputs.latest-deploy-success-tag }}
      base_ref: ${{ inputs.base_ref }}
      is_rollback: true
