name: Go - CD IssueOps

# Inspired from https://github.com/github/branch-deploy

on:
  issue_comment:
    types:
      - created
  workflow_call: {}

defaults:
  run:
    shell: bash

jobs:
  dispatch:
    name: Dispatch IssueOps commands
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      command: ${{ steps.issue-comment-dispatch.outputs.command }}
      continue: ${{ steps.issue-comment-dispatch.outputs.continue }}
      base_ref: ${{ steps.issue-comment-dispatch.outputs.base_ref }}
      ref: ${{ steps.issue-comment-dispatch.outputs.ref }}
      sha: ${{ steps.issue-comment-dispatch.outputs.sha }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Issue comment dispatch
        id: issue-comment-dispatch
        uses: kemadev/workflows-and-actions/.github/actions/issue-comment-dispatch@main
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ github.event.comment.id }}
          comment-body: ${{ github.event.comment.body }}

  pulumi:
    name: Run pulumi command
    needs:
      - dispatch
    if: ${{ needs.dispatch.outputs.continue == 'true' && (needs.dispatch.outputs.command == 'preview' || needs.dispatch.outputs.command == 'up') }}
    permissions:
      contents: write
      pull-requests: write
      deployments: write
      packages: write
    uses: kemadev/workflows-and-actions/.github/workflows/go-cd.yaml@main
    with:
      command: ${{ needs.dispatch.outputs.command }}
      sha: ${{ needs.dispatch.outputs.sha }}
      ref: ${{ needs.dispatch.outputs.ref }}
      base_ref: ${{ needs.dispatch.outputs.base_ref }}
      issue-comment-id: ${{ github.event.comment.id }}
