name: Go - CD IssueOps

on:
  issue_comment:
    types:
      - created
  workflow_call: {}

concurrency:
  group: go-cd-issueops

defaults:
  run:
    shell: bash

jobs:
  dispatch:
    name: Dispatch IssueOps commands
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.dispatch-issueops-commands.outputs.continue }}
      noop: ${{ steps.dispatch-issueops-commands.outputs.noop }}
      deployment_id: ${{ steps.dispatch-issueops-commands.outputs.deployment_id }}
      environment: ${{ steps.dispatch-issueops-commands.outputs.environment }}
      sha: ${{ steps.dispatch-issueops-commands.outputs.sha }}
      comment_id: ${{ steps.dispatch-issueops-commands.outputs.comment_id }}
      initial_reaction_id: ${{ steps.dispatch-issueops-commands.outputs.initial_reaction_id }}
      actor_handle: ${{ steps.dispatch-issueops-commands.outputs.actor_handle }}
    permissions:
      pull-requests: write
      deployments: write
      contents: write
      checks: read
      statuses: read
    steps:
      - name: Receive IssueOps commands
        id: dispatch-issueops-commands
        uses: github/command@v2
        with:
          command: /deploy
          param_separator: ' '
          skip_reviews: true
          skip_ci: true
          permissions: write,admin
          skip_completing: true

  build-code:
    name: Build code
    needs: dispatch
    if: ${{ needs.dispatch.outputs.continue == 'true' }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.dispatch.outputs.sha }}
          fetch-depth: 0
      - name: Build code
        id: build
        uses: kemadev/workflows-and-actions/.github/actions/go-build@main

  get-deploys-list:
    name: Get deploys list
    needs:
      - dispatch
      - build-code
    if: ${{ needs.dispatch.outputs.continue == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    outputs:
      deployment-dirs-list: ${{ steps.get-deploys-list.outputs.deployment-dirs-list }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.dispatch.outputs.sha }}
          fetch-depth: 0
      - name: Get deploys list
        id: get-deploys-list
        uses: kemadev/workflows-and-actions/.github/actions/go-get-deploys-list@main

  deploy:
    name: Deploy
    needs:
      - dispatch
      - get-deploys-list
    if: ${{ needs.dispatch.outputs.continue == 'true' }}
    permissions:
      contents: read
      packages: read
      pull-requests: write
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    strategy:
      matrix:
        deploy: ${{ fromJSON(needs.get-deploys-list.outputs.deployment-dirs-list) }}
      max-parallel: 1
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.dispatch.outputs.sha }}
      - name: Go deploy
        id: go-deploy
        uses: kemadev/workflows-and-actions/.github/actions/go-deploy@main
        if: ${{ needs.dispatch.outputs.continue == 'true' }}
        with:
          noop: ${{ needs.dispatch.outputs.noop }}
          environment: ${{ needs.dispatch.outputs.environment }}
