name: Go - CD

on:
  workflow_dispatch:
    inputs:
      command:
        description: Command to run
        type: string
        default: up
      sha:
        description: SHA to deploy
        type: string
        default: latest
      ref:
        description: Ref to deploy
        type: string
        default: main
      base_ref:
        description: Base ref to deploy
        type: string
        default: main
      enable_rollback:
        description: Enable rollback in case of deployment failure
        type: boolean
        default: true
      issue-comment-id:
        description: Issue comment ID
        type: number
      rollback:
        description: Wether to rollback instead of deploying
        type: boolean
        default: false
  workflow_call:
    inputs:
      command:
        description: Command to run
        type: string
        default: up
      sha:
        description: SHA to deploy
        type: string
        default: latest
      ref:
        description: Ref to deploy
        type: string
        default: main
      base_ref:
        description: Base ref to deploy
        type: string
        default: main
      enable_rollback:
        description: Enable rollback in case of deployment failure
        type: boolean
        default: true
      issue-comment-id:
        description: Issue comment ID
        type: number
      rollback:
        description: Wether to rollback instead of deploying
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    if: ${{ inputs.rollback != 'true' }}
    permissions:
      contents: read
      deployments: write
      pull-requests: write
      packages: write
    uses: kemadev/workflows-and-actions/.github/workflows/go-pulumi.yaml@main
    with:
      command: ${{ inputs.command }}
      sha: ${{ inputs.sha }}
      ref: ${{ inputs.ref }}
      base_ref: ${{ inputs.base_ref }}
      comment-id: ${{ inputs.issue-comment-id }}

  tag-deploy-success:
    name: Tag deploy success
    needs:
      - deploy
    if: ${{ inputs.base_ref == 'main' && inputs.command == 'up' && needs.deploy.result == 'success' && inputs.rollback != 'true' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Tag deploy success
        id: tag-deploy-success
        uses: kemadev/workflows-and-actions/.github/actions/tag-deploy-success@main
        with:
          deployed-ref: ${{ inputs.base_ref }}

  prepare-rollback:
    name: Prepare rollback
    needs:
      - deploy
    runs-on: ubuntu-latest
    outputs:
      rollback-ref: ${{ steps.get-latest-successful-deployment-tag.outputs.rollback-ref }}
    permissions:
      contents: read
    # if: ${{ always() && ((inputs.command == 'up' && inputs.enable_rollback == 'true') || inputs.rollback == 'true') }}
    if: ${{ always() && inputs.command == 'up' }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base_ref }}
      - name: Get latest successful deployment tag
        id: get-latest-successful-deployment-tag
        run: |
          declare rollback_ref
          if [[ "${{ inputs.rollback }}" != "true" ]]; then
            rollback_ref="$(git tag --list "deploy-success-${{ inputs.base_ref }}-*" | sort -V | tail -n 1)"
          else
            if [[ "${{ inputs.sha }}" == "latest" ]]; then
              rollback_ref="$(git tag --list "deploy-success-${{ inputs.base_ref }}-*" | sort -V | tail -n 2 | head -n 1)"
            else
              rollback_ref="${{ inputs.sha }}"
            fi
          fi
          if [[ -z "${rollback_ref}" ]]; then
            echo "No successful deployment found for branch ${{ inputs.base_ref }}"
            exit 1
          fi
          echo "Latest successful deployment tag is ${rollback_ref}"
          echo "rollback-ref=${rollback_ref}" >> "${GITHUB_OUTPUT}"

  rollback:
    name: Rollback
    needs:
      - prepare-rollback
    permissions:
      contents: read
      deployments: write
      pull-requests: write
      packages: write
    uses: kemadev/workflows-and-actions/.github/workflows/go-pulumi.yaml@main
    with:
      command: up
      sha: ${{ needs.prepare-rollback.outputs.rollback-ref }}
      ref: ${{ needs.prepare-rollback.outputs.rollback-ref }}
      base_ref: ${{ inputs.base_ref }}
      is-rollback: true
      comment-id: ${{ inputs.issue-comment-id }}
