name: Go - CD IssueOps

on:
  issue_comment:
    types:
      - created
  workflow_call: {}

defaults:
  run:
    shell: bash

jobs:
  dispatch:
    name: Dispatch IssueOps commands
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      command: ${{ steps.issue-comment-dispatch.outputs.command }}
      continue: ${{ steps.issue-comment-dispatch.outputs.continue }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Issue comment dispatch
        id: issue-comment-dispatch
        uses: kemadev/workflows-and-actions/.github/actions/issue-comment-dispatch@main
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ github.event.comment.id }}
          comment-body: ${{ github.event.comment.body }}

  pulumi:
    name: Run pulumi command
    needs:
      - dispatch
    if: ${{ (needs.dispatch.outputs.continue == 'true') && (needs.dispatch.outputs.command == 'preview' || needs.dispatch.outputs.command == 'up') }}
    permissions:
      contents: write
      pull-requests: write
      deployments: write
      packages: write
    uses: kemadev/workflows-and-actions/.github/workflows/go-cd.yaml@main
    with:
      command: ${{ needs.dispatch.outputs.command }}
      sha: ${{ github.event.issue.pull_request.head.sha }}
      base_ref: ${{ github.event.issue.pull_request.base.ref }}
      ref: ${{ github.event.issue.pull_request.head.ref }}
      enable_rollback: true

  debug:
    name: Debug
    needs:
      - dispatch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Debug
        run: |
          echo "Command: ${{ needs.dispatch.outputs.command }}"
          echo "Continue: ${{ needs.dispatch.outputs.continue }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Comment ID: ${{ github.event.comment.id }}"
          echo "Comment body: ${{ github.event.comment.body }}"
          echo "PR head SHA: ${{ github.event.issue.pull_request.head.sha }}"
          echo "PR base ref: ${{ github.event.issue.pull_request.base.ref }}"
          echo "PR head ref: ${{ github.event.issue.pull_request.head.ref }}"
          echo "op: ${{ (needs.dispatch.outputs.continue == 'true') && (needs.dispatch.outputs.command == 'preview' || needs.dispatch.outputs.command == 'up') }}"
          echo "needs.dispatch.outputs.continue: ${{ needs.dispatch.outputs.continue }}"
          echo "needs.dispatch.outputs.command: ${{ needs.dispatch.outputs.command }}"
