name: Housekeep - Update release packages list

on:
  schedule:
    # Each day at 3:00 AM
    - cron: 0 3 * * *
  workflow_call:
    inputs:
      directories_to_ignore:
        description: Directories that should not be considered. Should be a comma-separated list.
        type: string
        required: false
        default: 'deploy'
  workflow_dispatch:
    inputs:
      directories_to_ignore:
        description: Directories that should not be considered. Should be a comma-separated list.
        type: string
        required: false
        default: 'deploy'


defaults:
  run:
    shell: bash

env:
  RELEASE_PLEASE_CONFIG_DIR: config/release-please
  RELEASE_PLEASE_CONFIG_FILE: release-please-config.json

jobs:
  update-release-packages-list:
    name: Update release packages list
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Update release packages list
        id: update-release-packages-list
        run: |
          touch ${{ env.RELEASE_PLEASE_CONFIG_DIR }}/release-please.json.tmp
          declare -a go_mod_files
          mapfile -t go_mod_files < <(find . -name 'go.mod' | sed 's|./||')
          declare -a valid_go_mod_files_dirs
          IFS=',' read -r -a directories_to_ignore <<< "${{ github.event.inputs.directories_to_ignore }}"
          for go_mod_file in "${go_mod_files[@]}"; do
            ignore=false
            for directory_to_ignore in "${directories_to_ignore[@]}"; do
              if [[ "${go_mod_file}" == "${directory_to_ignore}"* ]]; then
                ignore=true
                break
              fi
            done
            if [ "${ignore}" = false ]; then
              valid_go_mod_files_dirs+=("$(dirname "${go_mod_file}")")
            fi
          done
          if [ ${#valid_go_mod_files_dirs[@]} -eq 0 ]; then
            echo "No valid go.mod files found"
            exit 1
          fi
          jq --argjson go_mod_files "$(printf '%s\n' "${valid_go_mod_files_dirs[@]}" | jq -R . | jq -s 'map({(.): {}}) | add')" '. + {
            packages: $go_mod_files
          }' ${{ env.RELEASE_PLEASE_CONFIG_DIR }}/${{ env.RELEASE_PLEASE_CONFIG_FILE }} > ${{ env.RELEASE_PLEASE_CONFIG_DIR }}/${{ env.RELEASE_PLEASE_CONFIG_FILE }}.tmp
          mv ${{ env.RELEASE_PLEASE_CONFIG_DIR }}/${{ env.RELEASE_PLEASE_CONFIG_FILE }}.tmp ${{ env.RELEASE_PLEASE_CONFIG_DIR }}/${{ env.RELEASE_PLEASE_CONFIG_FILE }}
      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          title: ':robot: Update release packages list'
          body: |
            ## :pencil: New packages to be released!

            Check out the new packages that will be tracked for releases, and merge if everything looks good!
          commit-message: 'feat(release): update release packages list'
          sign-commits: true
