name: Housekeep - Report failed workflows

on:
  workflow_run:
    workflows:
      - '*'
    types:
      - completed
    branches:
      - main
  workflow_call:
    inputs:
      HEAD_BRANCH:
        description: Head branch
        type: string
        required: true
      WORKFLOW_NAME:
        description: Workflow name
        type: string
        required: true
      WORKFLOW_RUN_TITLE:
        description: Workflow run title
        type: string
        required: true
      CONCLUSION:
        description: Conclusion
        type: string
        required: true
      HTML_URL:
        description: HTML URL
        type: string
        required: true
      CREATED_AT:
        description: Created at
        type: string
        required: true
      UPDATED_AT:
        description: Updated at
        type: string
        required: true
      ACTOR_TYPE:
        description: Actor type
        type: string
        required: true
      ACTOR_HTML_URL:
        description: Actor HTML URL
        type: string
        required: true
      TRIGGERING_ACTOR_TYPE:
        description: Triggering actor type
        type: string
        required: true
      TRIGGERING_ACTOR_HTML_URL:
        description: Triggering actor HTML URL
        type: string
        required: true

defaults:
  run:
    shell: bash

env:
  HOUSEKEEP_FAILED_WORKFLOWS_SCRIPT_DIR: .github/script/reusable/report-failed-workflows

permissions:
  contents: read
  issues: write

jobs:
  report-failed-workflows:
    name: Report failed workflows
    permissions:
      contents: read
      issues: write
      concurrency:
        group: housekeep-report-failed-workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Checkout reusable workflow scripts and configs
        id: checkout-reusable-scripts-and-configs
        uses: kemadev/workflows-and-actions/.github/actions/checkout-reusable-scripts-and-configs@main
        with:
          reusable-diretories: '.github/script/reusable'
      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.HOUSEKEEP_FAILED_WORKFLOWS_SCRIPT_DIR}}/go.mod
          cache-dependency-path: ${{ env.HOUSEKEEP_FAILED_WORKFLOWS_SCRIPT_DIR}}/go.sum
      - name: Report failed workflows
        id: report-failed-workflows
        working-directory: ${{ env.HOUSEKEEP_FAILED_WORKFLOWS_SCRIPT_DIR }}
        env:
          GH_TOKEN: ${{ github.token }}
          HEAD_BRANCH: ${{ inputs.HEAD_BRANCH }}
          WORKFLOW_NAME: ${{ inputs.WORKFLOW_NAME }}
          WORKFLOW_RUN_TITLE: ${{ inputs.WORKFLOW_RUN_TITLE }}
          CONCLUSION: ${{ inputs.CONCLUSION }}
          HTML_URL: ${{ inputs.HTML_URL }}
          CREATED_AT: ${{ inputs.CREATED_AT }}
          UPDATED_AT: ${{ inputs.UPDATED_AT }}
          ACTOR_TYPE: ${{ inputs.ACTOR_TYPE }}
          ACTOR_HTML_URL: ${{ inputs.ACTOR_HTML_URL }}
          TRIGGERING_ACTOR_TYPE: ${{ inputs.TRIGGERING_ACTOR_TYPE }}
          TRIGGERING_ACTOR_HTML_URL: ${{ inputs.TRIGGERING_ACTOR_HTML_URL }}
        run: |
          go run ./...
