name: Housekeep - Report stale branches

on:
  schedule:
    # Each day at 3:00 AM
    - cron: 0 3 * * *
  workflow_call: {}
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  report-stale-branches:
    name: Report stale branches
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Checkout reusable workflow scripts and configs
        id: checkout-reusable-scripts-and-configs
        uses: kemadev/workflows-and-actions/.github/actions/checkout-reusable-scripts-and-configs@main
      - name: Report stale branches
        id: warn-stale-branches
        env:
          GH_TOKEN: ${{ github.token }}
          DAYS_BEFORE_STALE: 30
        run: ./.github/script/reusable/report-stale-branches/report-stale-branches.sh
