name: Housekeep - Report stale branches

on:
  schedule:
    # Each day at 3:00 AM
    - cron: 0 3 * * *
  workflow_call: {}
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

env:
  HOUSEKEEP_STALE_BRANCHES_SCRIPT_DIR: .github/script/reusable/report-stale-branches

permissions:
  contents: read
  issues: write

jobs:
  report-stale-branches:
    name: Report stale branches
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Checkout reusable workflow scripts and configs
        id: checkout-reusable-scripts-and-configs
        uses: kemadev/workflows-and-actions/.github/actions/checkout-reusable-scripts-and-configs@main
        with:
          reusable-diretories: '.github/script/reusable'
      - name: Set up Go
        uses: actions/setup-go@v5
        id: setup-go
        with:
          go-version-file: ${{ env.HOUSEKEEP_STALE_BRANCHES_SCRIPT_DIR }}/go.mod
          cache-dependency-path: ${{ env.HOUSEKEEP_STALE_BRANCHES_SCRIPT_DIR }}/go.sum
      - name: Report stale branches
        id: warn-stale-branches
        env:
          GH_TOKEN: ${{ github.token }}
        working-directory: ${{ env.HOUSEKEEP_STALE_BRANCHES_SCRIPT_DIR }}
        run: |
          go run ./...
