name: Issue - Auto-assign

on:
  workflow_call: {}
  issues:
    types:
      - opened
      - reopened

defaults:
  run:
    shell: bash

jobs:
  auto-assign:
    name: Auto-assign to issue
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Auto-assign to issue
        id: auto-assign
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -f .github/CODEOWNERS ]; then
            echo "CODEOWNERS file found"
          else
            echo "CODEOWNERS file not found"
            exit 1
          fi
          declare repo_code_owner
          repo_code_owner="$(cat .github/CODEOWNERS | grep -oP '^\*\s+\K[@a-zA-Z/]+$')"
          if [ -n "${repo_code_owner}" ]; then
            echo "Assigning issue to ${repo_code_owner}"
            gh issue edit --repo "${{ github.repository }}" --issue "${{ github.event.issue.number }}" --assignee "${repo_code_owner}"
          else
            echo "No default CODEOWNER found"
            exit 1
          fi
