name: Markdown - CI

on:
  schedule:
    # Each day at 3:00 AM
    - cron: 0 3 * * *
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - unlocked
    paths:
      - "**.md"
  workflow_call: {}
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  lint-markdown-files:
    name: Lint markdown files
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Checkout reusable workflow scripts and configs
        id: checkout-reusable-scripts-and-configs
        uses: kemadev/workflows-and-actions/.github/actions/checkout-reusable-scripts-and-configs@main
        with:
          reusable-diretories: "config/reusable"
      - name: Lint markdown files
        id: lint-markdown-files
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          config: ./config/reusable/.markdownlint.yaml
          globs: |
            **/*.md
            #**/CHANGELOG.md
