name: Release

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    concurrency:
      group: release
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Release
        id: release
        uses: kemadev/workflows-and-actions/.github/actions/release@main
