name: Housekeep - Sync repository template

on:
  schedule:
    # Each day at 3:00 AM
    - cron: 0 3 * * *
  workflow_call: {}
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  sync-repo-template:
    name: Sync repository template
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout-main
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout
        id: checkout-template
        uses: actions/checkout@v4
        with:
          path: template
      - name: Sync repository template
        id: sync-repo-template
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./.github/script/reusable/housekeep-sync-repo-template/sync-repo-template.sh
