name: Website - CI

on:
  pull_request:
    paths:
      - "deploy/**.go"
  workflow_call: {}
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

env:
  MOZ_HTTP_OBSERVATORY_REPO: mdn/mdn-http-observatory
  WEBSITE_SECURITY_REPORT_FILE: ./dist/website-security-report.json
  SECURITY_SCRIPT_DIR: ./.github/script/website-ci

jobs:
  report-security:
    name: Report security
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Get dependency package.json and package-lock.json
        id: get-deps-lockfile
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api repos/${{ env.MOZ_HTTP_OBSERVATORY_REPO }}/contents/package.json | jq -r '.content' | base64 -d > package.json
          gh api repos/${{ env.MOZ_HTTP_OBSERVATORY_REPO }}/contents/package-lock.json | jq -r '.content' | base64 -d > package-lock.json
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: package.json
          cache-dependency-path: package-lock.json
      # From https://github.com/actions/setup-node/issues/416#issuecomment-1997465465
      - name: Setup node_modules cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install dependencies
        id: install-dependencies
        run: npm install @${{ env.MOZ_HTTP_OBSERVATORY_REPO }}
      - name: Check website security headers
        id: website-security
        run: |
          ./node_modules/.bin/mdn-http-observatory-scan mdn.dev > ${{ env.WEBSITE_SECURITY_REPORT_FILE }}
      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./.github/script/website-ci/go.mod
          cache-dependency-path: ./.github/script/website-ci/go.sum
      - name: Report security
        id: report-security
        # Run only on PRs, don't run on forks or dependabot as they don't have write access to the repository
        if: github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork && github.actor != 'dependabot[bot]'
        working-directory: ${{ env.SECURITY_SCRIPT_DIR }}
        env:
          WEBSITE_SECURITY_REPORT_FILE: ../../../${{ env.WEBSITE_SECURITY_REPORT_FILE }}
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
        run: go run report-security.go
