name: Checkout reusable workflow scripts and configs
description: Get reusable scripts and configs from the reusable workflows repository

author: kemadev
branding:
  icon: download-cloud
  color: blue

inputs:
  reusable-diretories:
    description: List of directories to copy from the reusable workflows repository. Should be a space separated list of directories.
    required: false
    default: '.github/script/reusable config/reusable'

runs:
  using: composite
  steps:
    - name: Checkout reusable workflow scripts and configs
      id: checkout-reusable-scripts-and-configs
      uses: actions/checkout@v4
      with:
        repository: kemadev/workflows-and-actions
        path: ${{ github.workspace }}/dist/workflows-and-actions
    - name: Copy reusable scripts and configs
      id: copy-reusable-scripts-and-configs
      shell: bash
      run: |
        echo "Copying reusable scripts and configs for directories: ${{ inputs.reusable-diretories }}"
        for dir in ${{ inputs.reusable-diretories }}; do
          declare dest="${dir%/*}"
          echo "Copying ${dir} to ${dest}"
          cp -r "${{ github.workspace }}/dist/workflows-and-actions/${dir}" "${dest}"
        done
    - name: Ignore git changes
      id: ignore-git-changes
      shell: bash
      run: |
        echo "Ignoring changes to keep git clean"
        for dir in ${{ inputs.reusable-diretories }}; do
          if [ -f "${dir}/PURPOSE.md" ]; then
            echo "Ignoring changes to ${dir}/PURPOSE.md"
            git update-index --assume-unchanged "${dir}/PURPOSE.md"
          fi
        done
