name: Checkout reusable workflow scripts and configs
description: Get reusable scripts and configs from the reusable workflows repository

author: kemadev
branding:
  icon: download-cloud
  color: blue

runs:
  using: composite
  steps:
    - name: Checkout reusable workflow scripts and configs
      id: checkout-reusable-scripts-and-configs
      uses: actions/checkout@v4
      with:
        repository: kemadev/workflows-and-actions
        path: ${{ github.workspace }}/dist/workflows-and-actions
    - name: Copy reusable scripts and configs
      id: copy-reusable-scripts-and-configs
      shell: bash
      run: |
        cp -r "${{ github.workspace }}/dist/workflows-and-actions/.github/script/reusable" .github/script
        cp -r "${{ github.workspace }}/dist/workflows-and-actions/config/reusable" config/reusable
    - name: Ignore git changes
      id: ignore-git-changes
      shell: bash
      run: |
        git update-index --assume-unchanged .github/script/reusable/PURPOSE.md
        git update-index --assume-unchanged config/reusable/PURPOSE.md
